### ISSUE TITLE
Game doesn't open when disconected from the internet

### ISSUE THREAD

**Issue by ChromanicAI** [Faugus/faugus-launcher#52]
Maybe this happens because the launcher doesn't proceed when checking the update status of proton and steam runtime because there is no way to retrieve the info from.

**Comment by Faugus** [comment]
You need to run a game at least once to update the Steam Runtime, the anti-cheat softwares and the Proton version.
After that, you can the game without internet connection.
Just make sure you're using a Proton version that you have downloaded.

**Comment by ChromanicAI** [comment]
Thanks

**Comment by Junzz0** [comment]
@Faugus 

Hello, I would like to ask if Faugus Launcher can provide a tutorial for completely offline operation.

I followed the documentation and placed proton-ge-custom in the ~/.local/share/Steam/compatibilitytools.d/ directory. Faugus Launcher can recognize it, but it gets stuck at the step involving the anti-cheat software, as it fails to download successfully due to network issues.

Heroic Games Launcher seems to allow disabling the anti-cheat software in the settings, mainly for running games purchased from GOG. However, Heroic Games Launcher does not support Wayland, so I want to switch to Faugus Launcher.

AI told me that I can use the environment variable PULSAR_NO_ANTI_CHEAT=1 to disable the anti-cheat software, which I will try later.

Thank you 👍🏼👍🏼

**Comment by Faugus** [comment]
You just need to run a game once with internet connection to download the necessary components.
After that you can disconnect from the internet.

About the anti-cheat, it won't use it if your game doesn't need it.
It will just download it.

**Comment by Junzz0** [comment]
> You just need to run a game once with internet connection to download the necessary components. After that you can disconnect from the internet.
> 
> About the anti-cheat, it won't use it if your game doesn't need it. It will just download it.

Thank you, but it still failed. PULSAR_NO_ANTI_CHEAT=1

```text
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Faugus/umu-launcher/releases (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f52033f52b0>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
```

This error is because I disabled the network in Flatpak, as github.com requires a proxy to be easily accessible. I'll see if there are other ways.
